# Generated by Django 2.0.4 on 2018-05-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='CONSULTANT_NAME',
            new_name='NAME',
        ),
    ]
