# Generated by Django 2.0.4 on 2018-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultant', '0002_auto_20180511_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='ID',
            field=models.CharField(choices=[('CD01', 'CD01'), ('CD02', 'CD02'), ('CD03', 'CD03'), ('CD04', 'CD04'), ('CD05', 'CD05'), ('CD06', 'CD06'), ('CD07', 'CD07'), ('CD08', 'CD08'), ('CD09', 'CD09'), ('CD10', 'CD10')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
