# Generated by Django 2.0.4 on 2018-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(blank=True, choices=[('cb01', 'CB01'), ('cb02', 'CB02'), ('cb03', 'CB03'), ('cb04', 'CB04'), ('cb05', 'CB05'), ('cb06', 'CB06'), ('cb07', 'CB07'), ('cb08', 'CB08')], max_length=20, null=True, unique=True)),
                ('CANDIDATE_NAME', models.CharField(max_length=150)),
                ('COUNTRY', models.CharField(choices=[('INDIA', 'INDIA'), ('US', 'US'), ('DUBAI', 'DUBAI'), ('SRI LANKA', 'SRI LANKA'), ('Bangladesh', 'Bangladesh')], max_length=25)),
                ('STATE', models.CharField(choices=[('UP', 'UP'), ('MP', 'MP'), ('TAMIL_NAADU', 'TAMIL_NADDU'), ('DELHI', 'DELHI'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('CITY', models.CharField(choices=[('MORADABAD', 'MORADABAD'), ('GHAZIABAD', 'GHAZIABAD'), ('MUMBAI', 'MUMBAI'), ('CHENNAI', 'CHENNAI'), ('DELHI', 'DELHI'), ('WASHINGTON', 'WASHINGTON'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('PINCODE', models.IntegerField()),
                ('MAIL_ID', models.EmailField(max_length=254)),
                ('MOBILE1', models.IntegerField()),
                ('MOBILE2', models.IntegerField()),
                ('FATHER_NAME', models.CharField(max_length=20)),
                ('COURSES_INTERESTED', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.TECH', 'B.TECH'), ('PHD', 'PHD'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('DIPLOMA', 'DIPLOMA'), ('MBBS', 'MBBS')], default='OTHERS', max_length=50)),
                ('PREFFERED_LOCATION', models.CharField(choices=[('MORADABAD', 'MORADABAD'), ('GHAZIABAD', 'GHAZIABAD'), ('MUMBAI', 'MUMBAI'), ('CHENNAI', 'CHENNAI'), ('DELHI', 'DELHI'), ('WASHINGTON', 'WASHINGTON'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=30)),
            ],
        ),
    ]
