# Generated by Django 2.0.4 on 2018-05-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_auto_20180511_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CID',
            field=models.CharField(blank=True, choices=[('CB01', 'CB01'), ('CB02', 'CB02'), ('CB03', 'CB03'), ('CB04', 'CB04'), ('CB05', 'CB05'), ('CB06', 'CB06'), ('CB07', 'CB07'), ('CB08', 'CB08')], max_length=20, null=True, unique=True),
        ),
    ]
