# Generated by Django 2.0.4 on 2018-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20180508_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.CharField(max_length=20)),
                ('NAME', models.CharField(max_length=150)),
                ('STREET', models.CharField(max_length=25)),
                ('CITY', models.CharField(max_length=20)),
                ('STATE', models.CharField(max_length=20)),
                ('PINCODE', models.IntegerField()),
                ('COUNTRY', models.CharField(max_length=20)),
                ('MAILID', models.EmailField(max_length=254)),
                ('MOBILE1', models.IntegerField()),
                ('MOBILE2', models.IntegerField()),
                ('FNAME', models.CharField(max_length=20)),
                ('COURSEINTERESTED', models.CharField(max_length=30)),
                ('PREFFEREDLOCATION', models.CharField(max_length=30)),
            ],
        ),
    ]
