# Generated by Django 2.0.4 on 2018-05-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
